/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import java.sql.SQLException;
import java.sql.Connection;
import config.Database;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc9
 */
public class order extends javax.swing.JDialog {

    private DefaultTableModel DftTblModel_ListMasakan;
    private String SQL;
    
    /**
     * Creates new form order
     */
    public order(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listmasakan();
        tgl();
        jam();
        txtiduser.setEnabled(false);
        txtidorder.setEnabled(false);
        lblnomeja.setVisible(false);
        txtnomeja.setVisible(false);
        txtidorder.setText("ORD-"+ GenerateRandomString());
    }
    
    public void baru(){
        lblidmasakan.setText("-");        
        lblnama.setText("-");        
        lblharga.setText("-");
        txtketerangan.setText(null);
        buttonGroup1.clearSelection();
        txtnomeja.setText(null);
        lblnomeja.setVisible(false);
        txtnomeja.setVisible(false);
        txtidorder.setText("ORD-"+ GenerateRandomString());
    }

    public static String GenerateRandomString() {
    // It will generate 6 digit random Number.
    // from 0 to 999999
    Random rnd = new Random();
    int number = rnd.nextInt(9999);

    // this will convert any number sequence into 6 character.
    return String.format("%04d", number);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_masakan = new javax.swing.JTable();
        txtiduser = new javax.swing.JTextField();
        btnpesan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbljam = new javax.swing.JLabel();
        lbltgl = new javax.swing.JLabel();
        txtidorder = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblharga = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        dtp = new javax.swing.JRadioButton();
        dlv = new javax.swing.JRadioButton();
        lblidmasakan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbljumlah = new javax.swing.JLabel();
        lblnomeja = new javax.swing.JLabel();
        txtketerangan = new javax.swing.JTextField();
        txtnomeja = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Order Pelanggan");

        jLabel4.setText("Tanggal  :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ORDER");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ID user : ");

        tbl_masakan.setBackground(new java.awt.Color(204, 204, 204));
        tbl_masakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Masakan", "Masakan", "Harga", "Status Makanan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_masakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_masakanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_masakan);

        btnpesan.setText("PESAN SEKARANG");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        jLabel7.setText("| Pilih Masakan");

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jLabel8.setText("ID order :");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("CARI");

        lbljam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbljam.setForeground(new java.awt.Color(255, 0, 0));
        lbljam.setText("-");

        lbltgl.setBackground(new java.awt.Color(204, 255, 255));
        lbltgl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbltgl.setText("-");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("| Keterangan ");

        lblharga.setText("-");

        lblnama.setText("-");

        buttonGroup1.add(dtp);
        dtp.setText("Di Tempat");
        dtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtpMouseClicked(evt);
            }
        });

        buttonGroup1.add(dlv);
        dlv.setText("Delivery");
        dlv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dlvMouseClicked(evt);
            }
        });

        lblidmasakan.setText("-");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("ID Masakan         ");

        lbljumlah.setText("Jumlah Pesan");

        lblnomeja.setText("No Meja");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Nama Masakan   ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Harga                    ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidmasakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblharga, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dlv)
                                .addComponent(dtp))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblnomeja)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnomeja, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbljumlah)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblidmasakan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnama)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblharga)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(dtp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dlv)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbljumlah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomeja)
                    .addComponent(txtnomeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(311, 311, 311)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtidorder))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(130, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnlogout))
                                    .addComponent(btnpesan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltgl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbljam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbltgl))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbljam)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtidorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnlogout)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_masakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_masakanMouseClicked
        // TODO add your handling code here:
        String status;
        
        int baris = tbl_masakan.getSelectedRow();
        lblidmasakan.setText(DftTblModel_ListMasakan.getValueAt(baris, 0).toString());
        lblnama.setText(DftTblModel_ListMasakan.getValueAt(baris, 1).toString());
        lblharga.setText(DftTblModel_ListMasakan.getValueAt(baris, 2).toString());
        status = DftTblModel_ListMasakan.getValueAt(baris, 3).toString();
        
        btnpesan.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        lblidmasakan.setVisible(true);
        lblharga.setVisible(true);
        dtp.setVisible(true);
        dlv.setVisible(true);
        lbljumlah.setVisible(true);
        txtketerangan.setVisible(true);
        
        if(status.equals("Kosong")) {
         jLabel12.setVisible(false);
         jLabel13.setVisible(false);
         jLabel14.setVisible(false);
         lblidmasakan.setVisible(false);
         lblnama.setText("STATUS MAKANAN KOSONG");
         lblharga.setVisible(false);
         btnpesan.setVisible(false);
         dtp.setVisible(false);
         dlv.setVisible(false);
         lbljumlah.setVisible(false);
         txtketerangan.setVisible(false);
         lblnomeja.setVisible(false);
         txtnomeja.setVisible(false);
        }
    }//GEN-LAST:event_tbl_masakanMouseClicked

    private void dlvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dlvMouseClicked
        // TODO add your handling code here:
        lblnomeja.setVisible(false);
        txtnomeja.setVisible(false);
    }//GEN-LAST:event_dlvMouseClicked

    private void dtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtpMouseClicked
        // TODO add your handling code here:
        lblnomeja.setVisible(true);
        txtnomeja.setVisible(true);
    }//GEN-LAST:event_dtpMouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txtcariKeyReleased

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        
//        jika cekbox ditempat true
        if (dtp.isSelected()){
//            lakukan validasi
         if (txtidorder.getText().isEmpty() || 
         lblidmasakan.getText().isEmpty() ||
         lblnama.getText().isEmpty() || 
         lblharga.getText().isEmpty() || 
         txtketerangan.getText().isEmpty() || 
         txtnomeja.getText().isEmpty())  {
             
         JOptionPane.showMessageDialog(rootPane,"Masih ada data yang kosong, wajib diisi","Informasi",JOptionPane.WARNING_MESSAGE);
//        sukses validasi insert data
         } else {
            java.sql.Connection DB = new Database().connect();
            try {
            java.sql.PreparedStatement stmt = DB.prepareStatement("INSERT INTO `order` VALUES ('"+txtidorder.getText()+"', '"+txtnomeja.getText()+"', '"+lbltgl.getText()+"', '"+txtiduser.getText()+"', '"+txtketerangan.getText()+"', 'Ditempat')");  
            java.sql.PreparedStatement stmt2 = DB.prepareStatement("INSERT INTO detail_order VALUES (null,'"+txtidorder.getText()+"','"+lblidmasakan.getText()+"','"+txtketerangan.getText()+"','Ditempat')");
            try {
                stmt.executeUpdate();
                stmt2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                baru();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) { }
        }
//         jika cekbox ditempat false
     } else {
//lakukan validasi
         if (txtidorder.getText().isEmpty() || 
         lblidmasakan.getText().isEmpty() ||
         lblnama.getText().isEmpty() || 
         lblharga.getText().isEmpty() || 
         txtketerangan.getText().isEmpty()){
             
         JOptionPane.showMessageDialog(rootPane,"Masih ada data yang kosong, wajib diisi","Informasi",JOptionPane.WARNING_MESSAGE);
//        sukses validasi insert data
         } else {
            java.sql.Connection DB = new Database().connect();
            try {
            java.sql.PreparedStatement stmt = DB.prepareStatement("INSERT INTO `order` VALUES ('"+txtidorder.getText()+"', '0', '"+lbltgl.getText()+"', '"+txtiduser.getText()+"', '"+txtketerangan.getText()+"', 'Delivery')");  
            java.sql.PreparedStatement stmt2 = DB.prepareStatement("INSERT INTO detail_order VALUES (null,'"+txtidorder.getText()+"','"+lblidmasakan.getText()+"','"+txtketerangan.getText()+"','Ditempat')");
            try {
                stmt.executeUpdate();
                stmt2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                baru();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) { }
        }
     }  
    }//GEN-LAST:event_btnpesanActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"yakin ingin Logout ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        main m = new main(); 
        dispose();
        m.dispose();
        login l = new login();
        l.setVisible(true);
        } 
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                order dialog = new order(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpesan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dlv;
    private javax.swing.JRadioButton dtp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lblidmasakan;
    private javax.swing.JLabel lbljam;
    private javax.swing.JLabel lbljumlah;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblnomeja;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JTable tbl_masakan;
    private javax.swing.JTextField txtcari;
    public javax.swing.JTextField txtidorder;
    public javax.swing.JTextField txtiduser;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnomeja;
    // End of variables declaration//GEN-END:variables
    private void cari() {
     String cari = txtcari.getText();
     DefaultTableModel DftTblModel_ListMasakan = (DefaultTableModel) tbl_masakan.getModel();   
     DftTblModel_ListMasakan.setRowCount(0);
     tbl_masakan.setModel(DftTblModel_ListMasakan);
     
        java.sql.Connection DB = new Database().connect();
        try {
            java.sql.Statement stmt = DB.createStatement();
            SQL = "SELECT * FROM masakan WHERE id_masakan LIKE '%"+cari+"%' OR nama_masakan LIKE '%"+cari+"%' OR harga LIKE '%"+cari+"%' OR status_masakan LIKE '%"+cari+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            
            Object [] data = new Object[4];
                while(res.next()) {
                data[0] = res.getString("id_masakan");
                data[1] = res.getString("nama_masakan");
                data[2] = res.getInt("harga");
                data[3] = res.getString("status_masakan");
                DftTblModel_ListMasakan.addRow(data);
                
             }
        } catch (SQLException ex) {
        }
    }
    
    private void listmasakan() {
        DftTblModel_ListMasakan = new DefaultTableModel();
        DftTblModel_ListMasakan.addColumn("ID Masakan");
        DftTblModel_ListMasakan.addColumn("Masakan");
        DftTblModel_ListMasakan.addColumn("Harga");
        DftTblModel_ListMasakan.addColumn("Status Masakan");

        tbl_masakan.setModel(DftTblModel_ListMasakan);
        java.sql.Connection DB = new Database().connect();
        try {
            java.sql.Statement stmt = DB.createStatement();
            SQL = "SELECT * FROM masakan";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_ListMasakan.addRow(new Object[]{
                    res.getString("id_masakan"),
                    res.getString("nama_masakan"),
                    res.getString("harga"),
                    res.getString("status_masakan")
                });
            }
        } catch (Exception e) {

        }
}
    
    private void tgl() {
        lbltgl.setText(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
}
    private void jam() {
     Timer tt = new Timer();
     tt.scheduleAtFixedRate(new TimerTask() {

         @Override
         public void run() {
             lbljam.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
             
         }
     }, 0, 1000);
 }
}
